# Generated by Django 4.2.30 on 2026-08-26 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
        ("datasources", "0002_initial"),
        ("workspaces", "0001_initial"),
        ("sqlconsole", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedquery",
            name="sql",
            field=models.TextField(
                help_text="Run through the source's own read-only connection, never through Honeycomb's. See the class docstring."
            ),
        ),
        migrations.CreateModel(
            name="QueryRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sql",
                    models.TextField(
                        help_text="Exactly what was sent, not what was saved."
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("SUCCEEDED", "Succeeded"), ("FAILED", "Failed")],
                        max_length=16,
                    ),
                ),
                ("result_columns", models.JSONField(blank=True, default=list)),
                ("result_rows", models.JSONField(blank=True, default=list)),
                ("row_count", models.PositiveIntegerField(default=0)),
                (
                    "truncated",
                    models.BooleanField(
                        default=False,
                        help_text="True when the result hit a cap, so the rows here are a prefix rather than the answer.",
                    ),
                ),
                ("notice", models.CharField(blank=True, max_length=255)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="query_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "data_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="query_runs",
                        to="datasources.datasource",
                    ),
                ),
                (
                    "saved_query",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when the run came from a saved query. Cleared if that query is later deleted -- the history of what ran stays true.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs",
                        to="sqlconsole.savedquery",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="accounts.tenant",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="query_runs",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "query run",
                "verbose_name_plural": "query runs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["workspace", "-created_at"], name="queryrun_ws_recent"
                    )
                ],
            },
        ),
    ]
