"""
Django settings for Honeycomb project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from corsheaders.defaults import default_headers as cors_default_headers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

REPO_ROOT = BASE_DIR.parent


def _load_dotenv(path):
    """Read KEY=value lines from `path` into os.environ.

    Deliberately not python-dotenv: this needs to parse a handful of flat
    assignments, and a dependency that ships in every deployment to do that is
    not worth it.

    A real environment variable always wins over the file, so a deployment that
    injects config properly is never silently overridden by a stale `.env` left
    in the image.
    """
    try:
        lines = path.read_text(encoding='utf-8').splitlines()
    except OSError:
        return
    for line in lines:
        line = line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, _, value = line.partition('=')
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key:
            os.environ.setdefault(key, value)


_load_dotenv(REPO_ROOT / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

def _env_flag(name, default):
    return os.environ.get(name, default).lower() in ('1', 'true', 'yes', 'on')


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_flag('DJANGO_DEBUG', 'True')

# SECURITY WARNING: keep the secret key used in production secret!
# No usable default: a committed literal lets anyone holding the source forge a
# signed token or session for any account, so an unset key is fatal outside
# local development.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if not DEBUG:
        from django.core.exceptions import ImproperlyConfigured

        raise ImproperlyConfigured(
            'DJANGO_SECRET_KEY must be set when DEBUG is False.'
        )
    SECRET_KEY = 'django-insecure-local-dev-only'

# The JWT key is separate so it can be rotated (invalidating outstanding
# tokens) without also invalidating sessions, CSRF tokens and password-reset
# links, which are signed with SECRET_KEY.
JWT_SIGNING_KEY = os.environ.get('DJANGO_JWT_SIGNING_KEY') or SECRET_KEY

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if host.strip()
]

# Render injects the service's public hostname at run time. Adding it here
# means a deploy needs no hand-maintained host list, and a service rename
# cannot lock you out of your own API with a DisallowedHost.
RENDER_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_HOSTNAME and RENDER_HOSTNAME not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(RENDER_HOSTNAME)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Directly below SecurityMiddleware, per WhiteNoise's own instruction.
    # Render serves no static files itself, so without this the admin re-skin
    # 404s in production and the admin renders as unstyled Django.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Below AuthenticationMiddleware so the admin login view it wraps is the
    # fully-assembled one. DRF's throttles stop at /api/; this covers the one
    # unthrottled password prompt left, /admin/login/.
    'accounts.middleware.AdminLoginRateLimitMiddleware',
]

ROOT_URLCONF = 'Honeycomb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Project-level overrides, searched before any app's own templates.
        # templates/admin/base_site.html brands the admin -- it must win over
        # the copy django.contrib.admin ships, and APP_DIRS templates cannot
        # override another app's, so the directory has to be listed here.
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Honeycomb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
#
# PostgreSQL is the target. Row-level tenancy means every request filters on
# `tenant_id`, and SQLite serialises the whole database behind one writer lock,
# so concurrent tenants queue behind each other. Postgres also gives real
# partial indexes -- the `User` email uniqueness rules depend on them.
#
# Nothing in this project is Postgres-only, so SQLite still works for a
# throwaway run: set DJANGO_DB_ENGINE=sqlite.
#
# Configure with a single URL:
#   DATABASE_URL=postgres://user:password@host:5432/dbname
# or with the discrete DJANGO_DB_* variables below. DATABASE_URL wins when
# both are present.

DB_ENGINE = os.environ.get('DJANGO_DB_ENGINE', 'postgres').lower()

if DB_ENGINE in ('sqlite', 'sqlite3'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    _db_url = os.environ.get('DATABASE_URL')
    if _db_url:
        from urllib.parse import unquote, urlparse

        _parsed = urlparse(_db_url)
        _db = {
            'NAME': unquote(_parsed.path.lstrip('/')),
            'USER': unquote(_parsed.username or ''),
            'PASSWORD': unquote(_parsed.password or ''),
            'HOST': _parsed.hostname or 'localhost',
            'PORT': str(_parsed.port or 5432),
        }
    else:
        _db = {
            'NAME': os.environ.get('DJANGO_DB_NAME', 'honeycomb'),
            'USER': os.environ.get('DJANGO_DB_USER', 'honeycomb'),
            'PASSWORD': os.environ.get('DJANGO_DB_PASSWORD', ''),
            'HOST': os.environ.get('DJANGO_DB_HOST', 'localhost'),
            'PORT': os.environ.get('DJANGO_DB_PORT', '5432'),
        }

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            # Reuse connections instead of opening one per request. Postgres
            # forks a backend process per connection, so per-request connects
            # are the single most expensive thing a small Django app does.
            'CONN_MAX_AGE': int(os.environ.get('DJANGO_DB_CONN_MAX_AGE', '60')),
            # Persistent connections can outlive the server on the other end
            # (deploy, failover, idle timeout). Without this the first request
            # after that hits a dead socket and 500s.
            'CONN_HEALTH_CHECKS': True,
            'OPTIONS': {
                # Fail fast rather than hanging a worker on an unreachable host.
                'connect_timeout': int(
                    os.environ.get('DJANGO_DB_CONNECT_TIMEOUT', '10')
                ),
            },
            **_db,
        }
    }

    # Encryption in transit is not optional once the database is on another
    # host. Local development talks over loopback, where there is nothing to
    # intercept, so this only tightens outside DEBUG.
    if not DEBUG:
        DATABASES['default']['OPTIONS']['sslmode'] = os.environ.get(
            'DJANGO_DB_SSLMODE', 'require'
        )


# Cache
#
# Every rate limit in this project -- DRF's ScopedRateThrottle and the admin
# login limiter in accounts/middleware.py -- keeps its counters here, so the
# cache is a security control, not just a speed-up.
#
# SECURITY WARNING: LocMemCache is per *process*. Under runserver that is one
# process and the counters are exact, but a production deployment running N
# gunicorn workers gets N independent sets of counters, so every limit below is
# effectively multiplied by N. A real deployment must point this at a shared
# backend (Redis or Memcached) for the limits to mean what they say.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'honeycomb-default',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Authentication
# https://docs.djangoproject.com/en/4.2/topics/auth/customizing/

AUTH_USER_MODEL = 'accounts.User'

AUTHENTICATION_BACKENDS = [
    'accounts.backends.TenantAwareModelBackend',
]

# accounts.User.email is unique per tenant, not globally, so Django's stock
# check for a globally unique USERNAME_FIELD does not apply. The configured
# backend resolves the ambiguity explicitly (see accounts/backends.py).
SILENCED_SYSTEM_CHECKS = ['auth.W004']


# Django REST Framework / SimpleJWT

REST_FRAMEWORK = {
    # Reads the JWT from the hc_access cookie and enforces CSRF on unsafe
    # methods; falls back to the Authorization header for non-browser callers.
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'accounts.authentication.CookieJWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # ScopedRateThrottle keys anonymous requests by client IP, which is what
    # the unauthenticated auth endpoints need. Views opt in via throttle_scope.
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.ScopedRateThrottle',
    ),
    # Without this, DRF's get_ident() trusts X-Forwarded-For whenever the
    # header is present -- and a header is whatever the caller says it is, so
    # rotating it hands an attacker an unlimited number of throttle buckets and
    # every rate limit below becomes decorative. 0 means "no proxy in front of
    # Django, always key on REMOTE_ADDR". Raise it to the exact number of
    # trusted proxies when one is deployed (and make that edge proxy
    # *overwrite* X-Forwarded-For rather than append to it).
    'NUM_PROXIES': int(os.environ.get('DJANGO_NUM_PROXIES', '0')),
    'DEFAULT_THROTTLE_RATES': {
        'signin': '10/min',
        'signup': '5/hour',
        # Per-keystroke-ish: the wizard calls this once per step, and a user
        # correcting a typo calls it repeatedly. Creates nothing, so it is
        # capped for address-probing rather than for write volume.
        'signup_check': '40/min',
        # Both re-authenticate before acting, so the ceiling is aimed at an
        # attacker on an unlocked browser guessing the current password.
        'change_password': '5/hour',
        'change_email': '5/hour',
        # Read on every page load and written rarely; generous but bounded.
        'profile': '30/min',
        # One per expired access token, plus retries. An access token lives an
        # hour, so anything near this rate is a loop, not a user.
        'refresh': '30/min',
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    # Rotation is off deliberately. With BLACKLIST_AFTER_ROTATION False it is a
    # pure no-op: the rotated-away token stays valid for its full 7 days, so
    # the only effect would be extra cookie writes. Enabling real revocation
    # means ROTATE_REFRESH_TOKENS True, BLACKLIST_AFTER_ROTATION True and
    # re-adding 'rest_framework_simplejwt.token_blacklist' to INSTALLED_APPS;
    # until then, logout and change-password end the browser session without
    # invalidating tokens already issued (see accounts/views.py).
    'ROTATE_REFRESH_TOKENS': False,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'SIGNING_KEY': JWT_SIGNING_KEY,
}


# Auth cookies
#
# The access token lives in an httpOnly cookie so the Next.js middleware can
# gate /dashboard/** on the server, before any chrome renders -- middleware
# cannot read localStorage. httpOnly also puts the token out of reach of page
# scripts. See accounts/authentication.py for the CSRF consequence.

HC_ACCESS_COOKIE = 'hc_access'
HC_REFRESH_COOKIE = 'hc_refresh'
HC_COOKIE_SECURE = not DEBUG
# Lax works because the dev frontend and backend differ only by port, and
# SameSite is decided on the registrable domain ('localhost' for both). A
# production deployment that puts the API on a different site would need
# 'None' plus Secure, or an API served from the frontend's own domain.
HC_COOKIE_SAMESITE = 'Lax'


# CORS
# https://github.com/adamchainz/django-cors-headers

CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
]

# Required for cookie-borne auth: without it the browser drops the Set-Cookie
# on a cross-origin response and refuses to attach the cookies on the way back.
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = list(cors_default_headers)
if 'x-csrftoken' not in CORS_ALLOW_HEADERS:
    # The double-submit header the frontend echoes from the csrftoken cookie.
    CORS_ALLOW_HEADERS.append('x-csrftoken')


# CSRF

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
]

# In production the browser talks only to the frontend's origin: Next.js
# rewrites /api/* through to this service, so requests arrive same-site and the
# Lax cookies above keep working. That origin still has to be trusted here,
# because CsrfViewMiddleware checks the forwarded Origin header, not the host.
# Comma-separated, each with its scheme: https://honeycomb-web.onrender.com
for _origin in os.environ.get('DJANGO_PUBLIC_ORIGINS', '').split(','):
    _origin = _origin.strip().rstrip('/')
    if _origin and _origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(_origin)
        # Harmless when the proxy makes every call same-origin; needed the
        # moment anything calls the API directly.
        if _origin not in CORS_ALLOWED_ORIGINS:
            CORS_ALLOWED_ORIGINS.append(_origin)

# Render terminates TLS at its edge and forwards plain HTTP. Without this
# Django sees an http:// request, so request.is_secure() is False, Secure
# cookies are never set and SECURE_SSL_REDIRECT loops forever.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# False on purpose: the frontend has to read this cookie to echo it back in the
# X-CSRFToken header. Knowing the token grants nothing by itself -- it only
# proves the caller could read a cookie scoped to this site.
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SAMESITE = 'Lax'


# Response hardening
#
# These three cost nothing on plain HTTP, so they are unconditional: an API that
# only sets them in production is an API nobody ever sees misbehave until it is
# too late to notice cheaply. The frontend sets its own equivalents (plus a CSP)
# in next.config.mjs for everything it serves.
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'
X_FRAME_OPTIONS = 'DENY'


# Production hardening
#
# Guarded because every one of these breaks plain-HTTP local development.
# With DEBUG=False and a real DJANGO_SECRET_KEY,
# "/Users/shubhambiswas/Desktop/HONEYCOMB BACKEND/.venv/bin/python manage.py
# check --deploy" should report no issues.

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Project-level assets, on top of whatever the installed apps ship. The admin
# skin lives here rather than inside `accounts` because it belongs to no app --
# it restyles django.contrib.admin, which cannot hold it.
STATICFILES_DIRS = [BASE_DIR / 'static']

# Where collectstatic gathers everything for a real deployment. Unused by
# runserver, which serves from the directories above directly.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Hashed filenames plus long-lived cache headers, and gzip/brotli siblings
# built at collectstatic time. Only outside DEBUG: the manifest backend raises
# on any file collectstatic has not seen, which would break runserver.
if not DEBUG:
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
