# Generated by Django 4.2.30 on 2026-09-03 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mcp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mcpkey",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "MCP key",
                "verbose_name_plural": "MCP keys",
            },
        ),
    ]
