# Generated by Django 4.2.30 on 2026-10-01 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0003_oauthclient_oauthgrant_oauthtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthtoken',
            name='family_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mcpactivity',
            name='connector',
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name='mcpactivity',
            name='tool_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AddIndex(
            model_name='mcpactivity',
            index=models.Index(fields=['tenant', '-created_at'], name='mcpact_tenant_time_idx'),
        ),
    ]
