# Generated by Django 4.2.30 on 2026-08-26 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("POSTGRES", "PostgreSQL"),
                            ("MYSQL", "MySQL"),
                            ("BIGQUERY", "BigQuery"),
                            ("SNOWFLAKE", "Snowflake"),
                            ("S3", "Amazon S3"),
                            ("HTTP", "HTTP endpoint"),
                        ],
                        default="POSTGRES",
                        max_length=16,
                    ),
                ),
                ("host", models.CharField(blank=True, max_length=255)),
                ("port", models.PositiveIntegerField(blank=True, null=True)),
                ("database", models.CharField(blank=True, max_length=255)),
                ("username", models.CharField(blank=True, max_length=255)),
                (
                    "secret_name",
                    models.CharField(
                        blank=True,
                        help_text="Key this connection's password is stored under in the secret manager. Never the password itself.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Not tested"),
                            ("CONNECTED", "Connected"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
