# Generated by Django 4.2.30 on 2026-08-31 11:03

import connections.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "connector",
                    models.CharField(
                        db_index=True,
                        help_text='Registry slug, e.g. "github". Not a foreign key: the connector catalog is code, not rows.',
                        max_length=48,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=80)),
                (
                    "creds_enc",
                    models.TextField(
                        blank=True,
                        help_text="Fernet ciphertext of a JSON credential object. Never read this field directly -- use creds().",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("error", "Error")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("last_error", models.TextField(blank=True)),
                (
                    "disabled_tools",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tool names switched off for this instance. Stored as the deny-list rather than the allow-list so a connector that gains a tool exposes it by default instead of silently hiding it from every existing connection.",
                    ),
                ),
                (
                    "endpoint_slug",
                    models.CharField(
                        db_index=True,
                        default=connections.models.generate_endpoint_slug,
                        editable=False,
                        max_length=24,
                        unique=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL once the person who created this connection is deleted. The connection itself belongs to the tenant, not to them, so it must outlive their account.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["tenant", "connector"],
                        name="connection_tenant_conn_idx",
                    )
                ],
            },
        ),
    ]
