# Generated by Django 4.2.30 on 2026-08-31 11:37

import connections.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("connections", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConnectorOAuthState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "connector",
                    models.CharField(
                        help_text="Registry slug the flow was started for. Re-checked at the callback so a nonce minted for one connector cannot be redeemed against another.",
                        max_length=48,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        default=connections.models.generate_oauth_state,
                        editable=False,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Stamped the instant the nonce is redeemed, before the token exchange runs, so a replayed callback cannot mint a second connection from the same code.",
                        null=True,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="The organization the resulting connection will land in, captured when the flow started. The callback is unauthenticated and cannot be asked.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connector_oauth_states",
                        to="accounts.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Who started the flow; becomes the connection's created_by.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connector_oauth_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
