# Generated by Django 4.2.30 on 2026-09-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connections", "0002_connectoroauthstate"),
    ]

    operations = [
        migrations.AddField(
            model_name="connection",
            name="account_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Remote account this connection is bound to. Never a secret.",
                max_length=190,
            ),
        ),
        migrations.AddConstraint(
            model_name="connection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("account_key", ""), _negated=True),
                fields=("tenant", "connector", "account_key"),
                name="uniq_connection_per_account",
            ),
        ),
    ]
