# Generated by Django 4.2.30 on 2026-09-03 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("connections", "0004_backfill_account_key"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="connectoroauthstate",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "OAuth handshake",
                "verbose_name_plural": "OAuth handshakes",
            },
        ),
    ]
