# Generated by Django 4.2.30 on 2026-10-01 01:17

"""Write tools become opt-in per connection.

The backfill keeps today's behaviour exactly: every write tool that is not in a
connection's disabled_tools right now -- i.e. that someone switched on -- is
recorded as enabled. From here on, a write tool a connector gains in a later
release is absent from that list, and therefore off, on every existing
connection.

It reads the connector registry rather than a frozen copy because the catalog
is code, not rows; a connector that no longer exists simply contributes nothing.
"""
from django.db import migrations, models


def backfill(apps, schema_editor):
    from connectors import registry

    Connection = apps.get_model('connections', 'Connection')
    for row in Connection.objects.all().only('id', 'connector', 'disabled_tools'):
        connector = registry.get(row.connector)
        if connector is None:
            continue
        disabled = set(row.disabled_tools or [])
        enabled = [name for name in connector.write_tools if name not in disabled]
        if enabled:
            Connection.objects.filter(pk=row.pk).update(enabled_write_tools=enabled)


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0006_meta_suite_write_tools_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='enabled_write_tools',
            field=models.JSONField(blank=True, default=list, help_text='Write tools a person has switched on for this instance.'),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
