# Generated by Django 4.2.30 on 2026-09-01 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=80)),
                ("token_prefix", models.CharField(db_index=True, max_length=16)),
                ("token_hash", models.CharField(db_index=True, max_length=64)),
                ("version", models.CharField(blank=True, max_length=32)),
                ("platform", models.CharField(blank=True, max_length=64)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("rss_mb", models.FloatField(blank=True, null=True)),
                ("active_jobs", models.IntegerField(default=0)),
                (
                    "paused",
                    models.BooleanField(
                        default=False,
                        help_text="Set from the dashboard. The worker reads it on its next poll and stops claiming new jobs; running jobs finish.",
                    ),
                ),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forager_workers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen_at", "name"],
            },
        ),
        migrations.CreateModel(
            name="CrawlJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("seed_url", models.URLField(max_length=500)),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("claimed", "Claimed"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("source", models.CharField(default="ui", max_length=16)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("pages_crawled", models.IntegerField(default=0)),
                ("pages_queued", models.IntegerField(default=0)),
                ("urls_discovered", models.IntegerField(default=0)),
                ("links_found", models.IntegerField(default=0)),
                ("failures", models.IntegerField(default=0)),
                ("bytes_downloaded", models.BigIntegerField(default=0)),
                ("status_counts", models.JSONField(blank=True, default=dict)),
                ("cancel_requested", models.BooleanField(default=False)),
                ("error", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forager_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="accounts.tenant",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="foraging.worker",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CrawlEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seq",
                    models.BigIntegerField(
                        help_text="Monotonic per job. The console polls with ?since=<seq>, so this is what makes the stream resumable and gap-free."
                    ),
                ),
                ("at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("fetch", "Fetch"),
                            ("warn", "Warn"),
                            ("error", "Error"),
                            ("done", "Done"),
                        ],
                        default="info",
                        max_length=8,
                    ),
                ),
                ("text", models.CharField(max_length=500)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("size_bytes", models.IntegerField(blank=True, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="foraging.crawljob",
                    ),
                ),
            ],
            options={
                "ordering": ["seq"],
            },
        ),
        migrations.CreateModel(
            name="CrawlPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=2000)),
                ("url_hash", models.BinaryField(db_index=True, max_length=16)),
                ("depth", models.IntegerField(default=0)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("content_type", models.CharField(blank=True, max_length=100)),
                ("response_time_ms", models.IntegerField(blank=True, null=True)),
                ("size_bytes", models.IntegerField(default=0)),
                ("redirect_count", models.IntegerField(default=0)),
                ("final_url", models.URLField(blank=True, max_length=2000)),
                ("discovered_via", models.CharField(blank=True, max_length=16)),
                ("inlinks", models.IntegerField(default=0)),
                ("outlinks", models.IntegerField(default=0)),
                (
                    "content_hash",
                    models.BinaryField(blank=True, max_length=16, null=True),
                ),
                ("error", models.CharField(blank=True, max_length=200)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="foraging.crawljob",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["job", "status_code"], name="forage_page_job_status_idx"
                    ),
                    models.Index(
                        fields=["job", "-size_bytes"], name="forage_page_job_size_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="crawlpage",
            constraint=models.UniqueConstraint(
                fields=("job", "url_hash"), name="forage_page_unique_url"
            ),
        ),
        migrations.AddIndex(
            model_name="crawljob",
            index=models.Index(
                fields=["tenant", "status", "-created_at"], name="forage_job_tenant_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crawljob",
            index=models.Index(
                fields=["status", "created_at"], name="forage_job_queue_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crawlevent",
            index=models.Index(fields=["job", "seq"], name="forage_event_job_seq_idx"),
        ),
        migrations.AddConstraint(
            model_name="crawlevent",
            constraint=models.UniqueConstraint(
                fields=("job", "seq"), name="forage_event_unique_seq"
            ),
        ),
    ]
