# Generated by Django 4.2.30 on 2026-09-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foraging", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawlpage",
            name="canonical",
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name="crawlpage",
            name="flesch_reading_ease",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="crawlpage",
            name="h1_1",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="crawlpage",
            name="h1_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="crawlpage",
            name="h2_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="crawlpage",
            name="images",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="crawlpage",
            name="images_missing_alt",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="crawlpage",
            name="indexability",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="crawlpage",
            name="indexability_status",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="crawlpage",
            name="issues",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="crawlpage",
            name="language",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="crawlpage",
            name="meta_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="crawlpage",
            name="meta_description_length",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="crawlpage",
            name="meta_description_pixel_width",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="crawlpage",
            name="meta_robots",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="crawlpage",
            name="readability",
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name="crawlpage",
            name="structured_data_types",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="crawlpage",
            name="text_ratio",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="crawlpage",
            name="title",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="crawlpage",
            name="title_length",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="crawlpage",
            name="title_pixel_width",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="crawlpage",
            name="word_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="crawlpage",
            index=models.Index(
                fields=["job", "indexability"], name="forage_page_job_index_idx"
            ),
        ),
    ]
