# Generated by Django 4.2.30 on 2026-09-01 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
        ("foraging", "0002_crawlpage_canonical_crawlpage_flesch_reading_ease_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrawlSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=80)),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "rules",
                    models.JSONField(
                        default=list,
                        help_text="List of {field, op, value}. Validated when applied, since the column set a rule may name belongs to CrawlPage and not to this row.",
                    ),
                ),
                (
                    "match",
                    models.CharField(
                        choices=[("all", "All rules"), ("any", "Any rule")],
                        default="all",
                        max_length=3,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="crawlpage",
            name="closest_similarity",
            field=models.FloatField(
                default=0,
                help_text="Jaccard estimate against the nearest other page, 0-1.",
            ),
        ),
        migrations.AddField(
            model_name="crawlpage",
            name="hreflang_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="crawlpage",
            name="hreflang_issues",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="crawlpage",
            name="link_score",
            field=models.FloatField(
                default=0,
                help_text="Internal PageRank scaled 0-100. Zero means not computed, not unlinked -- an orphan scores above zero.",
            ),
        ),
        migrations.AddField(
            model_name="crawlpage",
            name="near_duplicates",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="crawlpage",
            name="structured_data_errors",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="crawlpage",
            name="structured_data_findings",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="crawlpage",
            name="structured_data_warnings",
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="crawlpage",
            index=models.Index(
                fields=["job", "-link_score"], name="forage_page_job_score_idx"
            ),
        ),
        migrations.AddField(
            model_name="crawlsegment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forager_segments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="crawlsegment",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="accounts.tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="crawlsegment",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name"), name="forage_segment_unique_name"
            ),
        ),
    ]
