# Generated by Django 4.2.30 on 2026-09-15 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("foraging", "0003_crawlsegment_crawlpage_closest_similarity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawlpage",
            name="final_status_code",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="crawlpage",
            name="http_version",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="crawlpage",
            name="js_added_links",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="crawlpage",
            name="js_added_words",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="crawlpage",
            name="js_console_errors",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="crawlpage",
            name="js_dependent",
            field=models.BooleanField(
                default=False,
                help_text="Rendering added links or text the raw HTML did not have.",
            ),
        ),
        migrations.AddField(
            model_name="crawlpage",
            name="js_rendered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="crawlpage",
            name="rendered_word_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="crawlpage",
            name="response_headers",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="CrawlLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_id", models.BigIntegerField()),
                ("from_hash", models.BinaryField(max_length=16)),
                ("to_hash", models.BinaryField(max_length=16)),
                ("to_url", models.CharField(max_length=2000)),
                ("anchor", models.CharField(blank=True, max_length=500, null=True)),
                ("rel", models.CharField(blank=True, max_length=100)),
                ("kind", models.CharField(max_length=16)),
                ("internal", models.BooleanField(default=True)),
                ("position", models.IntegerField(default=0)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="foraging.crawljob",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["job", "from_hash"], name="forage_link_from_idx"
                    ),
                    models.Index(fields=["job", "to_hash"], name="forage_link_to_idx"),
                    models.Index(fields=["job", "kind"], name="forage_link_kind_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="crawllink",
            constraint=models.UniqueConstraint(
                fields=("job", "source_id"), name="forage_link_unique_source"
            ),
        ),
    ]
