# Generated by Django 4.2.30 on 2026-09-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foraging", "0004_page_detail_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawljob",
            name="pause_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="crawljob",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("claimed", "Claimed"),
                    ("running", "Running"),
                    ("paused", "Paused"),
                    ("done", "Done"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="queued",
                max_length=16,
            ),
        ),
    ]
