# Generated by Django 4.2.30 on 2026-09-26 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reports.layout


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('client', models.CharField(blank=True, help_text='The client this report is for. Used to group and filter reports.', max_length=120)),
                ('layout', models.JSONField(blank=True, default=list)),
                ('filters', models.JSONField(blank=True, default=reports.layout.default_filters)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='NULL once the person who made this report is deleted. The report belongs to the organization, so it outlives their account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_edited', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['tenant', '-updated_at'], name='report_tenant_updated_idx')],
            },
        ),
    ]
